In [1]:
import numpy as np

In [ ]:
x = [0,1,2,3,4]
print(x)

In [ ]:
y = np.array(x)
print(y)
print(type(y))
print(y*y)
print(y.size)
print(y.dtype)

In [ ]:
np.identity(n=5)

In [ ]:
np.ones(shape=[5,5])

In [ ]:
np.zeros(shape=[5,5])

In [ ]:
y = [0, 1, 2, 3, 4]
# y * y

In [ ]:
np.ndim(y)

In [2]:
x = np.array([[1,2,3,4],[21,22,23,24],[31,32,33,34],[41,42,43,44],[51,52,53,54]])
np.ndim(x)

2

In [4]:
print(x)
print(x.shape)

[[ 1  2  3  4]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]]
(5, 4)


In [5]:
x.flatten()

array([ 1,  2,  3,  4, 21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43, 44, 51,
       52, 53, 54])

In [7]:
x
x.dtype

dtype('int64')

In [8]:
x.T

array([[ 1, 21, 31, 41, 51],
       [ 2, 22, 32, 42, 52],
       [ 3, 23, 33, 43, 53],
       [ 4, 24, 34, 44, 54]])

In [9]:
x + 100

array([[101, 102, 103, 104],
       [121, 122, 123, 124],
       [131, 132, 133, 134],
       [141, 142, 143, 144],
       [151, 152, 153, 154]])

In [10]:
x * 2

array([[  2,   4,   6,   8],
       [ 42,  44,  46,  48],
       [ 62,  64,  66,  68],
       [ 82,  84,  86,  88],
       [102, 104, 106, 108]])

In [11]:
x ** 2

array([[   1,    4,    9,   16],
       [ 441,  484,  529,  576],
       [ 961, 1024, 1089, 1156],
       [1681, 1764, 1849, 1936],
       [2601, 2704, 2809, 2916]])

In [12]:
x + x

array([[  2,   4,   6,   8],
       [ 42,  44,  46,  48],
       [ 62,  64,  66,  68],
       [ 82,  84,  86,  88],
       [102, 104, 106, 108]])

In [13]:
x * x

array([[   1,    4,    9,   16],
       [ 441,  484,  529,  576],
       [ 961, 1024, 1089, 1156],
       [1681, 1764, 1849, 1936],
       [2601, 2704, 2809, 2916]])

In [14]:
print(np.mean(x))
print(x.mean())

30.5
30.5


In [15]:
np.mean(x,axis=0)

array([29., 30., 31., 32.])

In [16]:
import pandas as pd
import os
print(os.getcwd())

C:\Users\LJCR


In [26]:
# pd por convención
nuevo_campos = ['id_poliza', 'codigo_estado', 'condado', 'limite_terremoto',
    'limite_huracan', 'limite_inundacion', 'limite_incendio',
    'valor_asegurado_2011', 'valor_asegurado_2012',
    'deducible_terremoto', 'deducible_huracan', 'deducible_inundacion', 'deducible_incendio',
    'latitud', 'longitud', 'tipo_propiedad', 'material_construccion', 'granularidad']


# Opción 1: Cambiar al directorio correcto
os.chdir(r'C:\Users\LJCR\Documents\GitHub\Datajupyer\Version01\sesion2\2.- Scientific Python Stack y Big Data Engineering')
data = pd.read_csv('FL_insurance_sample.csv',names=nuevo_campos,header=0)


In [27]:
data

,id_poliza,codigo_estado,condado,limite_terremoto,limite_huracan,limite_inundacion,limite_incendio,valor_asegurado_2011,valor_asegurado_2012,deducible_terremoto,deducible_huracan,deducible_inundacion,deducible_incendio,latitud,longitud,tipo_propiedad,material_construccion,granularidad
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3


In [28]:
print(data.info)

<bound method DataFrame.info of        id_poliza codigo_estado          condado  limite_terremoto  \
0         119736            FL      CLAY COUNTY          498960.0   
1         448094            FL      CLAY COUNTY         1322376.3   
2         206893            FL      CLAY COUNTY          190724.4   
3         333743            FL      CLAY COUNTY               0.0   
4         172534            FL      CLAY COUNTY               0.0   
...          ...           ...              ...               ...   
36629     404309            FL  PINELLAS COUNTY               0.0   
36630     465875            FL  PINELLAS COUNTY         1297057.5   
36631     791209            FL  PINELLAS COUNTY          173286.9   
36632     322627            FL  PINELLAS COUNTY         1499781.6   
36633     398149            FL  PINELLAS COUNTY          373488.3   

       limite_huracan  limite_inundacion  limite_incendio  \
0           498960.00           498960.0         498960.0   
1          132237

In [25]:
print(data.describe)

<bound method NDFrame.describe of        policyID statecode           county  eq_site_limit  hu_site_limit  \
0        119736        FL      CLAY COUNTY       498960.0      498960.00   
1        448094        FL      CLAY COUNTY      1322376.3     1322376.30   
2        206893        FL      CLAY COUNTY       190724.4      190724.40   
3        333743        FL      CLAY COUNTY            0.0       79520.76   
4        172534        FL      CLAY COUNTY            0.0      254281.50   
...         ...       ...              ...            ...            ...   
36629    404309        FL  PINELLAS COUNTY            0.0       88722.00   
36630    465875        FL  PINELLAS COUNTY      1297057.5     1297057.50   
36631    791209        FL  PINELLAS COUNTY       173286.9      173286.90   
36632    322627        FL  PINELLAS COUNTY      1499781.6     1499781.60   
36633    398149        FL  PINELLAS COUNTY       373488.3      373488.30   

       fl_site_limit  fr_site_limit    tiv_2011    ti

In [29]:
type(data)

pandas.DataFrame

In [30]:
s=pd.Series([0.10,1.20,2.23,3.4,4.5])
print(s)

0    0.10
1    1.20
2    2.23
3    3.40
4    4.50
dtype: float64


In [32]:
s1=pd.Series([0.10,1.20,2.23,3.4,4.5],index=["a","b","c","d","e"])

In [33]:
s1

a    0.10
b    1.20
c    2.23
d    3.40
e    4.50
dtype: float64

In [34]:
s1[['a','c']]

a    0.10
c    2.23
dtype: float64

In [45]:
s1[s1>2]


c    2.23
d    3.40
e    4.50
dtype: float64

In [53]:
data = pd.read_csv('./train.csv')
print(type(data))
print('- - '*10)
print(data.dtypes)

<class 'pandas.DataFrame'>
- - - - - - - - - - - - - - - - - - - - 
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object


In [48]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
nuevos_nombres = {
    'PassengerId': 'id_pasajero',
    'Survived': 'sobrevivio',
    'Pclass': 'clase',
    'Name': 'nombre',
    'Sex': 'genero',
    'Age': 'edad',
    'SibSp': 'hermanos_conyuge',
    'Parch': 'padres_hijos',
    'Ticket': 'ticket',
    'Fare': 'tarifa',
    'Cabin': 'cabina',
    'Embarked': 'embarque'
}

data.rename(columns= nuevo_campos,inplace=true)



data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200
