In [5]:
conda env list



# conda environments:
#
base                   /Users/ljcr/anaconda3
ds                   * /Users/ljcr/anaconda3/envs/ds
ds01                   /Users/ljcr/anaconda3/envs/ds01
ds_py                  /Users/ljcr/anaconda3/envs/ds_py


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
x = [0,1,2,3,4]
print(x)

[0, 1, 2, 3, 4]


In [8]:
y = np.array(x)
print(y)
print(type(y))
print(y*y)
print(y.size)
print(y.dtype)

[0 1 2 3 4]
<class 'numpy.ndarray'>
[ 0  1  4  9 16]
5
int64


In [9]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.ones(shape=[5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.zeros(shape=[5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
y = [0, 1, 2, 3, 4]
y * y

TypeError: can't multiply sequence by non-int of type 'list'

In [24]:
np.ndim(y)

1

TypeError: can't multiply sequence by non-int of type 'list'

In [42]:
x = np.array([[1,2,3,4],[21,22,23,24],[31,32,33,34],[41,42,43,44],[51,52,53,54]])

In [44]:
print(x)

[[ 1  2  3  4]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]]


In [45]:
x.flatten()

array([ 1,  2,  3,  4, 21, 22, 23, 24, 31, 32, 33, 34, 41, 42, 43, 44, 51,
       52, 53, 54])

In [46]:
x.dtype

dtype('int64')

In [47]:
x.T

array([[ 1, 21, 31, 41, 51],
       [ 2, 22, 32, 42, 52],
       [ 3, 23, 33, 43, 53],
       [ 4, 24, 34, 44, 54]])

In [48]:
x + 100

array([[101, 102, 103, 104],
       [121, 122, 123, 124],
       [131, 132, 133, 134],
       [141, 142, 143, 144],
       [151, 152, 153, 154]])

In [49]:
x * 2

array([[  2,   4,   6,   8],
       [ 42,  44,  46,  48],
       [ 62,  64,  66,  68],
       [ 82,  84,  86,  88],
       [102, 104, 106, 108]])

In [50]:
x ** 2

array([[   1,    4,    9,   16],
       [ 441,  484,  529,  576],
       [ 961, 1024, 1089, 1156],
       [1681, 1764, 1849, 1936],
       [2601, 2704, 2809, 2916]])

In [51]:
x + x

array([[  2,   4,   6,   8],
       [ 42,  44,  46,  48],
       [ 62,  64,  66,  68],
       [ 82,  84,  86,  88],
       [102, 104, 106, 108]])

In [52]:
x * x

array([[   1,    4,    9,   16],
       [ 441,  484,  529,  576],
       [ 961, 1024, 1089, 1156],
       [1681, 1764, 1849, 1936],
       [2601, 2704, 2809, 2916]])

In [56]:
print(np.mean(x))
print(x.mean())

30.5
30.5


In [59]:
np.mean(x,axis=0)

array([29., 30., 31., 32.])