In [1]:
import numpy as np
print(np.__version__)

2.4.2


In [2]:
print("hola")

hola


In [2]:
x = [0,1,2,3,4]

In [3]:
print(x)

[0, 1, 2, 3, 4]


In [4]:
print(type(x))

<class 'list'>


In [5]:
import numpy as np

In [6]:
y = np.array(x)

In [ ]:
y

array([0, 1, 2, 3, 4])

In [9]:
print(type(y))

<class 'numpy.ndarray'>


In [13]:
len(y)

5

In [14]:
len(x)

5

In [15]:
y*y

array([ 0,  1,  4,  9, 16])

In [16]:
y.dtype

dtype('int64')

In [17]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones(shape=[5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
zeros =   np.zeros(shape=[5,5])
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
np.ndim(zeros)

2

In [28]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
type(matriz)

list

In [30]:
x1 = np.array(matriz)

In [31]:
np.ndim(x1)

2

In [32]:
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(x1[-1,-1])


9


In [38]:
print(x1[-1,-1])

9


In [39]:
print(x1[1,2])

6


In [40]:
matriz = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

In [41]:
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
x


[0, 1, 2, 3, 4]

In [44]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
x1 = x1[:-1,:]

In [46]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
x2=x1.flatten()

In [49]:
print(x2)

[1 2 3 4 5 6]


In [50]:
x2.dtype

dtype('int64')

In [52]:
x2.T

array([1, 2, 3, 4, 5, 6])

In [53]:
x2

array([1, 2, 3, 4, 5, 6])