In [1]:
import numpy as np
print(np.__version__)

2.4.2


In [2]:
print("hola")

hola


In [2]:
x = [0,1,2,3,4]

In [3]:
print(x)

[0, 1, 2, 3, 4]


In [4]:
print(type(x))

<class 'list'>


In [5]:
import numpy as np

In [6]:
y = np.array(x)

In [ ]:
y

array([0, 1, 2, 3, 4])

In [9]:
print(type(y))

<class 'numpy.ndarray'>


In [13]:
len(y)

5

In [14]:
len(x)

5

In [15]:
y*y

array([ 0,  1,  4,  9, 16])

In [16]:
y.dtype

dtype('int64')

In [17]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones(shape=[5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
zeros =   np.zeros(shape=[5,5])
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
np.ndim(zeros)

2

In [28]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
type(matriz)

list

In [30]:
x1 = np.array(matriz)

In [31]:
np.ndim(x1)

2

In [32]:
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(x1[-1,-1])


9


In [38]:
print(x1[-1,-1])

9


In [39]:
print(x1[1,2])

6


In [40]:
matriz = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

In [41]:
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
x


[0, 1, 2, 3, 4]

In [44]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
x1 = x1[:-1,:]

In [46]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
x2=x1.flatten()

In [49]:
print(x2)

[1 2 3 4 5 6]


In [50]:
x2.dtype

dtype('int64')

In [52]:
x2.T

array([1, 2, 3, 4, 5, 6])

In [53]:
x2

array([1, 2, 3, 4, 5, 6])

In [3]:
x = -1
if x < 0:
    print ("x es negativo")
elif x ==0:
    print("x es 0")
elif x>= 5:
    print("x es igual 5")
else :
    print("x es cualquier numero")

x es negativo


In [1]:
bajos = [1, 2, 3, 4, 5]
altos = [6, 7, 8, 9, 10]
numeros = bajos + altos

In [2]:
print(numeros)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
for i in numeros:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [6]:
for i in numeros[:4]:
    print(i)

1
2
3
4


In [8]:
contador= 0
while contador<=3:
    print(contador)
    contador+=1

0
1
2
3


In [13]:
def f_saludar_usuario( name,age):
    print("hola %s , tu edad es  %s" %(name,age))

In [14]:
f_saludar_usuario('luis','28')

hola luis , tu edad es  28


In [15]:
class MiClase(object):
    """
    Mi clase doc
    """
    class_prop = "Propiedad de clase"

    def __init__(self, nombre=None, verbose=False) :
        """
        Documentacion de constructor
        """
        self.data = []
        self._private_data = []
        self._nombre = nombre
    
    def __del__(self):
        pass
    
    def __add__(self, a):
        pass
    
    def __getitem__(self, key):
        pass
    
    def function(self):
        """
        Documentacion de methodo
        """
        self._privada()
        print("Este mensaje se imprime desde la clase")
    
    def _privada(self):
        """
        Documentacion de methodo
        """
        print("Este mensaje se imprime desde la clase")
        
    @staticmethod
    def metodo_estatico():
        print("Statico, no tiene acceso a 'self'")
    
    @classmethod
    def verboso(cls):
        print("Metodo de clase")
        a = cls(verbose=False)
        del a.data
    
    @property
    def nombre(self):
        print("Calling nombre")
        return self._nombre
    
    @nombre.setter
    def nombre(self, a):
        self._nombre = a
        print("Calling setter")
    
    def algo(self):
        """
        doc de lo que hago
        """
        raise NotImplementedError()

In [18]:
mi_objeto = MiClase()
mi_objeto.data = 12
#mi_objeto.cls_list.append(1)
mi_objeto.function()
mi_objeto = MiClase()
#mi_objeto.cls_list.append(1)

Este mensaje se imprime desde la clase
Este mensaje se imprime desde la clase


In [29]:
import sys

num = sys.argv[1]
num = '123'


if num.isdigit() :
    num = int(num)
    print("num is int")
else : 
    print("el argumento solo puetener argumnentos")
    sys.exit(-1)

num is int


In [21]:
print(sys.argv[1])

--f=/Users/ljcr/Library/Jupyter/runtime/kernel-v3ced81597fd7577975deecc1002fc1e07e570e490.json


In [32]:
import sys
try:
    num = int(sys.argv[1])
except ValueError:
    print('El argumento uno solo puede tener numero')
    sys.exit(-1)

El argumento uno solo puede tener numero


SystemExit: -1

/Users/ljcr/anaconda3/envs/mpy/lib/python3.13/site-packages/IPython/core/interactiveshell.py:3755: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [36]:
try:
    print("PyMTY" + {})
except TypeError as err:
    print('Error : {}'.format(err))
    raise Exception('no se puede concaternar cadenas y diccionarios')

Error : can only concatenate str (not "dict") to str


Exception: no se puede concaternar cadenas y diccionarios

In [41]:
try:
    print("pymty")
    raise OSError('test')
    x=1+2
except OSError as e :
    print(e , "Error en el sistema operativo")
else:
    print("todo normnal")

pymty
test Error en el sistema operativo


In [7]:
_names = ["A","B","C","D","E"]
listAlphabet = {name:i for name,i in zip(_names,range(len(_names)+1))}


In [8]:
listAlphabet

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}

In [11]:
listaaa = (i for i in range(1,11))
print(listaaa)

<generator object <genexpr> at 0x10ed1e8c0>


In [12]:
next(listaaa)

1

In [13]:
next(listaaa)

2

In [14]:
next(listaaa)

3

In [15]:
for num,i in enumerate(listaaa,10):
    print("num",num)

num 10
num 11
num 12
num 13
num 14
num 15
num 16


In [16]:
next(listaaa)

StopIteration: 

In [2]:
filter01 = [primo for primo in range(1,30) if primo %2]
print(filter01)
print(type(filter01))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]
<class 'list'>


In [3]:
filter01


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [4]:
ñ_ñ=11

In [8]:
print(ñ_ñ)

11


In [7]:
print(type((1,2,3)))

<class 'tuple'>


In [10]:
print(tuple((1,2,3)))

(1, 2, 3)


In [11]:
None

In [19]:
print("Startup \n Studio ")

Startup 
 Studio 


In [20]:
collection = ([],[])

In [21]:
print(type(collection))

<class 'tuple'>


In [22]:
collection[0].append(1)

In [23]:
print(collection)

([1], [])


In [26]:
collection[1].append(2)

In [27]:
print(collection)

([1], [2])


In [29]:
nombre = "Joel Rivera"

In [40]:
nums = list(range(76,90+1))

In [41]:
nums

[76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]

In [42]:
nums[0:5]

[76, 77, 78, 79, 80]

In [47]:
nums[:5]

[76, 77, 78, 79, 80]

In [49]:
nums[4]

80

In [50]:
import string

In [ ]:
letters = list(string.ascii_letters)

In [53]:
print(letters)
print(len(letters))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
52


In [54]:
letters[:5]

['a', 'b', 'c', 'd', 'e']

In [56]:
letters[:-2]

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X']

In [57]:
letters[-1:0:-1]

['Z',
 'Y',
 'X',
 'W',
 'V',
 'U',
 'T',
 'S',
 'R',
 'Q',
 'P',
 'O',
 'N',
 'M',
 'L',
 'K',
 'J',
 'I',
 'H',
 'G',
 'F',
 'E',
 'D',
 'C',
 'B',
 'A',
 'z',
 'y',
 'x',
 'w',
 'v',
 'u',
 't',
 's',
 'r',
 'q',
 'p',
 'o',
 'n',
 'm',
 'l',
 'k',
 'j',
 'i',
 'h',
 'g',
 'f',
 'e',
 'd',
 'c',
 'b']

In [58]:
nombre= {}

In [ ]:
t=(1,0)
tupla_en_dict = {t:"Joel"}
print(type(tupla_en_dict))
print(type(tupla_en_dict[(1,0)]))
print(tupla_en_dict[(1,0)])


<class 'dict'>
<class 'str'>
Joel


In [67]:
tupla_en_dict

{(1, 0): 'Joel'}

In [69]:
tupla_en_dict["dasd"]=2221

In [70]:
tupla_en_dict


{(1, 0): 'Joel', 'dasd': 2221}

In [71]:
tupla_en_dict["a","b","c"]=2212321313

In [72]:
tupla_en_dict

{(1, 0): 'Joel', 'dasd': 2221, ('a', 'b', 'c'): 2212321313}