In [ ]:
#mamba install pandas numpy scikit-learn matplotlib jupyter boto3 

In [ ]:
import numpy as np


In [4]:
x = [0,1,2,3,4]
x

[0, 1, 2, 3, 4]

In [3]:
y=np.array(x)
y

array([0, 1, 2, 3, 4])

In [5]:
print(type(x))
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
print(x*2)
print(y*2)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0 2 4 6 8]


In [7]:
y*y

array([ 0,  1,  4,  9, 16])

In [8]:
y.size

5

In [9]:
y.dtype

dtype('int64')

In [10]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
x = np.array([[1.0,2,3],[4,5,6]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
x[1,2]

np.float64(6.0)

In [15]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
x.flatten()

array([1., 2., 3., 4., 5., 6.])

In [18]:
x.dtype

dtype('float64')

In [19]:
x.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [20]:
x+100

array([[101., 102., 103.],
       [104., 105., 106.]])

In [21]:
x*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [23]:
x + x

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [24]:
x*x

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

np.float64(3.5)

In [ ]:
np.mean(x,axis=0)

array([2.5, 3.5, 4.5])

In [30]:
np.mean(x,axis=1)

array([2., 5.])

In [31]:
x.std()

np.float64(1.707825127659933)

In [32]:
np.sum(x,axis=1)

array([ 6., 15.])

In [33]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
x.sum(axis=0)

array([5., 7., 9.])